# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-27 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_user_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favoritedby',
        ),
        migrations.AddField(
            model_name='recipe',
            name='favoritedby',
            field=models.ManyToManyField(related_name='favorites', to='recipe_app.User'),
        ),
    ]
