# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-28 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_myrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrecipe',
            name='serving_size',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
