# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-28 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_myrecipe_serving_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myrecipe',
            old_name='serving_size',
            new_name='servings',
        ),
    ]
